### ISSUE TITLE
compile with 0.24 crystal

### ISSUE THREAD

**Issue by kostya** [will/crystal-pg#116]
```
instantiating 'DB::ResultSet+#read((String | Nil):Class)'
in lib/db/src/db/result_set.cr:79: instantiating 'read()'

      value = read
              ^~~~

in lib/pg/src/pg/result_set.cr:78: instantiating 'PG::Decoders::Decoder#decode(IO::Sized, Int32)'

      value = decoder.decode(sized_io, col_bytesize)
                      ^~~~~~

in lib/pg/src/pg/decoder.cr:220: undefined method 'ticks' for Time

    JAN_1_2K_TICKS = Time.new(2000, 1, 1, kind: Time::Kind::Utc).ticks
                                                                 ^~~~~
```

**Comment by will** [comment]
Thanks. Do you know what ticks was renamed to?

**Comment by RX14** [comment]
@will we don't have ticks any more, it was an implementation detail. We changed how time was stored to seconds + microseconds in seperate fields. Why were you storing ticks?

**Comment by will** [comment]
Pg sends the time as a duration since Jan 1, 2000. I was using the ticks
constructor and adding the ticks between Unix and pg epochs.

**Comment by RX14** [comment]
@will you want to do `Time.now - Time.new(2000, 1, 1, kind: Time::Kind::Utc)` and then convert that `Time::Span` to whatever format PG wants.

**Comment by will** [comment]
I was more thinking of the `Time.epoch_ms` constructor. As an aside, that method might benefit from a single div_mod instruction. Not sure if llvm will recognize that optimization by itself, I haven't checked.

**Comment by RX14** [comment]
We have a divmod method that just returns `{x / y, x % y}`. LLVM will absolutely recognise that opimization and apply it.

**Comment by will** [comment]
Looking a bit more into it, Postgres has microsecond precision, and we've been losing some of that to go to the ticks. Using the `.epoch_ms` method would still be losing some precision, so the `new(sconds: , microsecons:)` is probably a better choice.

**Comment by will** [comment]
> We have a divmod method that just returns {x / y, x % y}. LLVM will absolutely recognise that opimization and apply it.

Yeah, but I was wondering if it knows to optimize it as two separate lines like in https://github.com/crystal-lang/crystal/blob/master/src/time.cr#L240-L241

**Comment by RX14** [comment]
@will probably. It'll probably not even use the instructions, just a few bit twiddles to avoid the expensive instructions entirely as you can do that when the divisor is a constant.

**Comment by will** [comment]
cafe58314bbbf0e6273963b1447e1c2fbeaf41ff fixes it, but also breaks support for earlier versions

**Comment by watzon** [comment]
Any progress on this?

**Comment by will** [comment]
Yeah the patch is there and referenced earlier in this thread, but I don’t
want to merge it to master because it breaks support for everything that’s
not 0.24

**Comment by watzon** [comment]
@will but everything that is 0.24, which is now the current stable version, will be broken without the merge. It's kinda pointless to try and maintain backwards compatibility at this point

**Comment by watzon** [comment]
Disregard my last comment

**Comment by will** [comment]
crystal-pg 0.14.0 has been released with support for crystal 0.24
